// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO1M2xY_olVMeJej5R1ZFdv4k8PbJeJTk',
    appId: '1:715997695551:web:7a2556cbf26724989b328a',
    messagingSenderId: '715997695551',
    projectId: 'ceg-forum',
    authDomain: 'ceg-forum.firebaseapp.com',
    storageBucket: 'ceg-forum.appspot.com',
    measurementId: 'G-3G72HGHZLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiu4z1wuW9O-wfvusiJ1f91U2TM5KVXwY',
    appId: '1:715997695551:android:b3e3a8a08601582e9b328a',
    messagingSenderId: '715997695551',
    projectId: 'ceg-forum',
    storageBucket: 'ceg-forum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIZXKPeeA32P1R2Q6o82xYJbGuBVpYkCA',
    appId: '1:715997695551:ios:7afb87ff056d0e749b328a',
    messagingSenderId: '715997695551',
    projectId: 'ceg-forum',
    storageBucket: 'ceg-forum.appspot.com',
    androidClientId: '715997695551-peh6q59fhv5qsks8hjgaq08b33mvmoue.apps.googleusercontent.com',
    iosClientId: '715997695551-gltkcqj5su9j7r1liv5v2tpfc0i4cooe.apps.googleusercontent.com',
    iosBundleId: 'com.example.cegForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIZXKPeeA32P1R2Q6o82xYJbGuBVpYkCA',
    appId: '1:715997695551:ios:7afb87ff056d0e749b328a',
    messagingSenderId: '715997695551',
    projectId: 'ceg-forum',
    storageBucket: 'ceg-forum.appspot.com',
    androidClientId: '715997695551-peh6q59fhv5qsks8hjgaq08b33mvmoue.apps.googleusercontent.com',
    iosClientId: '715997695551-gltkcqj5su9j7r1liv5v2tpfc0i4cooe.apps.googleusercontent.com',
    iosBundleId: 'com.example.cegForum',
  );
}
